### ISSUE TITLE
Support for topics, find strangers with common interests

### ISSUE THREAD

**Issue by FEFB-tech** [tavurth/OmegleTerminal#1]
First of all, thank you for putting together such an useful yet simply and elegant omegle client. For most us folks with low end machines it really makes a difference to be able to run web applications from the terminal.

That said, just a little request ... would you mind to add support for topics? to find strangers with common interests. I'll really appreciate that.
Cheers!

**Comment by tavurth** [comment]
Hi @FEFB-tech!

Thanks for the suggestion and for taking a look through my repositories!

Unfortunately the Omegle API has changed it's flow recently, which I've [outlined here](https://github.com/tavurth/OmegleTerminal/blob/master/connection.org).

Due to the addition of the recaptcha it's no longer as trivial as it used to be to implement a library such as this. 

I could probably find a way to sidestep the issue given a few days, but the introduction of such tech by the provider (Omegle) means that most solutions would likely become unstable over time.

I would suggest that if you'd really like this feature (chat from an external app), it would be a good idea to talk to the website owner about implementing a new open API, perhaps using a username and password.

In this way we could sidestep the captcha properly and still allow minimal spam.

Kind regards,
Will
